"""Regenerate PRH2 from the original Prisma archive. Requires numpy and msgpack.
Run from repository root: python3 scripts/generate-prisma-native.py
Bind matrices, not editable pose transforms, define the neutral skeleton.
"""
import base64
import gzip
import hashlib
import json
from pathlib import Path
import re
import struct
import zipfile

import msgpack
import numpy as np

source = Path('assets-source/prisma/Group.prisma')
with zipfile.ZipFile(source) as archive:
    names = [name for name in archive.namelist() if name.endswith('.pobject')]
    assert len(names) == 1
    data = msgpack.unpackb(archive.read(names[0])[4:], raw=False)
objects = {obj[0]: obj for obj in data[1]}
renderers = [(obj, component) for obj in data[1] for component in obj[2] if component[0] == 'PMeshRenderer']
assert len(renderers) == 1
renderer = {name: value for name, value, _ in renderers[0][1][1]}
joint_ids = json.loads(renderer['skinBones'])['ids']
mesh_id = json.loads(renderer['pMesh'])['id']
mesh, = [mesh for mesh in data[2] if mesh[0] == mesh_id]
assert len(joint_ids) == 31 and len(mesh[8]) == 3779
parents = [joint_ids.index(objects[joint][3]) if objects[joint][3] in joint_ids else -1 for joint in joint_ids]
# Unity/Prisma left-handed coordinates -> Three right-handed coordinates.
reflection = np.diag([1., 1., -1., 1.])
world = [reflection @ np.linalg.inv(np.array(matrix).reshape(4, 4, order='F')) @ reflection for matrix in mesh[10]]
local = [np.linalg.inv(world[parent]) @ matrix if parent >= 0 else matrix for parent, matrix in zip(parents, world)]
positions = np.array(mesh[8], dtype=np.float32)
positions[:, 2] *= -1
# Polygon triangulation is already supplied, with indices local to each polygon.
indices = []
corner_offset = triangle_offset = 0
for count in mesh[2]:
    triangle_count = (count - 2) * 3
    corners = mesh[4][corner_offset:corner_offset + count]
    for offset in range(triangle_offset, triangle_offset + triangle_count, 3):
        a, b, c = [corners[index] for index in mesh[7][offset:offset + 3]]
        indices.extend([a, c, b])
    corner_offset += count
    triangle_offset += triangle_count
assert corner_offset == len(mesh[4]) and triangle_offset == len(mesh[7])
assert len(indices) == 22662 and max(indices) < len(positions)
normals = np.zeros_like(positions)
for a, b, c in np.array(indices).reshape(-1, 3):
    normal = np.cross(positions[b] - positions[a], positions[c] - positions[a])
    normals[[a, b, c]] += normal
lengths = np.linalg.norm(normals, axis=1)
assert np.all(lengths > 0)
normals /= lengths[:, None]
skin = np.array(mesh[9])
assert np.all(skin[:, :4] >= 0) and np.all(skin[:, :4] < 31)
assert np.allclose(skin[:, 4:].sum(axis=1), 1, atol=1e-5)
packed = b'PRH2' + struct.pack('<4I', len(positions), len(indices), len(joint_ids), 1)
packed += np.array(parents, dtype=np.int8).tobytes()
packed += b''.join(np.array(matrix, dtype='<f4').flatten(order='F').tobytes() for matrix in local)
packed += positions.astype('<f4').tobytes() + normals.astype('<f4').tobytes()
packed += skin[:, :4].astype('u1').tobytes() + skin[:, 4:].astype('<f4').tobytes()
packed += np.array(indices, dtype='<u2').tobytes()
encoded = base64.b64encode(gzip.compress(packed, mtime=0)).decode('ascii')
# Preserve the established twelve-module packaging boundary.
chunk_size = ((len(encoded) + 47) // 48) * 4
for index in range(12):
    chunk = encoded[index * chunk_size:(index + 1) * chunk_size]
    Path(f'src/player/prisma-native/generated/part-{index + 1:02}.js').write_text('// Generated by scripts/generate-prisma-native.py; do not edit.\nexport default ' + json.dumps(chunk) + ';\n')
asset = Path('src/player/PrismaHumanoidAsset.js')
text = asset.read_text()
text = re.sub(r"PRISMA_HUMANOID_PACKED_SHA256 = '[^']+'", "PRISMA_HUMANOID_PACKED_SHA256 = '" + hashlib.sha256(packed).hexdigest() + "'", text)
asset.write_text(text)
print(f'Generated {len(packed)} bytes; SHA256 {hashlib.sha256(packed).hexdigest()}')
